# Generated by Django 5.2.15 on 2026-06-30 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('account_type', models.CharField(choices=[('B2B', 'Organisation'), ('B2C', 'Usage personnel')], default='B2B', max_length=3, verbose_name='type de compte')),
                ('questionnaire_version', models.CharField(choices=[('50', '50 items (~10 min)'), ('100', '100 items (~20 min)')], default='50', max_length=3, verbose_name='version du questionnaire')),
                ('language_default', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2, verbose_name='langue par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('role', models.CharField(choices=[('RH', 'Responsable RH'), ('MANAGER', 'Manager'), ('SOLO', 'Utilisateur solo')], default='RH', max_length=10, verbose_name='rôle')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2, verbose_name='langue')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='invité par')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
            },
        ),
    ]
