# Generated by Django 5.2.15 on 2026-07-03 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=2000, verbose_name='message')),
                ('page', models.CharField(blank=True, max_length=255, verbose_name="page d'origine")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.organization', verbose_name='organisation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'retour utilisateur',
                'verbose_name_plural': 'retours utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
