# Generated by Django 5.2.15 on 2026-07-03 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSSOConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False, verbose_name='activé')),
                ('display_name', models.CharField(help_text='Affiché sur le bouton « Se connecter avec… ».', max_length=100, verbose_name="nom d'affichage")),
                ('login_slug', models.SlugField(help_text="Utilisé dans l'URL de connexion SSO — doit être unique.", unique=True, verbose_name='identifiant de connexion')),
                ('issuer_url', models.URLField(help_text="Endpoint de découverte OIDC de votre fournisseur d'identité.", verbose_name="URL d'émetteur OIDC")),
                ('client_id', models.CharField(max_length=255, verbose_name='client ID')),
                ('client_secret', models.CharField(help_text='Jamais ré-affiché après saisie.', max_length=255, verbose_name='client secret')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_config', to='accounts.organization', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'configuration SSO',
                'verbose_name_plural': 'configurations SSO',
            },
        ),
    ]
