# Generated by Django 5.2.15 on 2026-07-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_orgssoconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='language_default',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('de', 'Deutsch')], default='fr', max_length=2, verbose_name='langue par défaut'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('de', 'Deutsch')], default='fr', max_length=2, verbose_name='langue'),
        ),
    ]
