# Generated by Django 5.2.15 on 2026-07-03 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_organization_language_default_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Pour vous y retrouver, ex. « Intégration ATS Greenhouse ».', max_length=100, verbose_name='nom')),
                ('key_prefix', models.CharField(max_length=12, unique=True, verbose_name='préfixe')),
                ('key_hash', models.CharField(max_length=64, verbose_name='empreinte de la clé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière utilisation')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='révoquée le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='accounts.organization', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'clé API',
                'verbose_name_plural': 'clés API',
                'ordering': ['-created_at'],
            },
        ),
    ]
