# Generated by Django 5.2.15 on 2026-07-03 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_organization_language_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'Essai'), ('active', 'Actif'), ('past_due', 'Paiement en retard'), ('canceled', 'Résilié')], default='trialing', max_length=10, verbose_name='statut')),
                ('trial_ends_at', models.DateTimeField(verbose_name="fin d'essai")),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, verbose_name='ID client Stripe')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, verbose_name='ID abonnement Stripe')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='fin de période en cours')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.organization', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
            },
        ),
    ]
