# Generated by Django 5.2.15 on 2026-07-06 20:54
#
# Passage au modèle freemium (US-E1-07 révisé) : plus d'essai 14 jours,
# plan gratuit permanent ≤ 25 personnes. Les abonnements "trialing"
# existants basculent sur le plan gratuit.

from django.db import migrations, models


def trialing_to_free(apps, schema_editor):
    Subscription = apps.get_model("billing", "Subscription")
    Subscription.objects.filter(status="trialing").update(status="free")


def free_to_trialing(apps, schema_editor):
    # Retour arrière best-effort : on ne peut pas reconstituer trial_ends_at.
    Subscription = apps.get_model("billing", "Subscription")
    Subscription.objects.filter(status="free").update(status="trialing")


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(trialing_to_free, free_to_trialing),
        migrations.RemoveField(
            model_name='subscription',
            name='trial_ends_at',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('free', 'Plan gratuit'), ('active', 'Actif'), ('past_due', 'Paiement en retard'), ('canceled', 'Résilié')], default='free', max_length=10, verbose_name='statut'),
        ),
    ]
