# Generated by Django 5.2.15 on 2026-06-30 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_fr', models.CharField(max_length=255, verbose_name='titre (FR)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='titre (EN)')),
                ('description_fr', models.TextField(blank=True, verbose_name='description (FR)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (EN)')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='département')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('archived', 'Archivé')], default='active', max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_positions', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.organization', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'poste',
                'verbose_name_plural': 'postes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PositionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('openness_min', models.PositiveSmallIntegerField(default=0)),
                ('openness_max', models.PositiveSmallIntegerField(default=100)),
                ('conscientiousness_min', models.PositiveSmallIntegerField(default=0)),
                ('conscientiousness_max', models.PositiveSmallIntegerField(default=100)),
                ('extraversion_min', models.PositiveSmallIntegerField(default=0)),
                ('extraversion_max', models.PositiveSmallIntegerField(default=100)),
                ('agreeableness_min', models.PositiveSmallIntegerField(default=0)),
                ('agreeableness_max', models.PositiveSmallIntegerField(default=100)),
                ('neuroticism_min', models.PositiveSmallIntegerField(default=0)),
                ('neuroticism_max', models.PositiveSmallIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='positions.position')),
            ],
            options={
                'verbose_name': 'profil de poste',
            },
        ),
    ]
