# Generated by Django 5.2.15 on 2026-06-30 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigFiveProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('openness', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ouverture')),
                ('conscientiousness', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='conscienciosité')),
                ('extraversion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='extraversion')),
                ('agreeableness', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='agréabilité')),
                ('neuroticism', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='neuroticisme')),
                ('questionnaire_version', models.CharField(choices=[('50', '50 items'), ('100', '100 items')], max_length=3)),
                ('algorithm_version', models.CharField(default='v1.0', max_length=20)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='big_five_profile', to='survey.questionnairelink')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='big_five_profile', to='teams.person')),
            ],
            options={
                'verbose_name': 'profil Big Five',
            },
        ),
    ]
