# Generated by Django 6.0.6 on 2026-07-01 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
        ('positions', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionFitResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('openness_fit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fit ouverture')),
                ('conscientiousness_fit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fit conscienciosité')),
                ('extraversion_fit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fit extraversion')),
                ('agreeableness_fit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fit agréabilité')),
                ('neuroticism_fit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fit neuroticisme')),
                ('overall_fit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fit global')),
                ('algorithm_version', models.CharField(default='v1.0', max_length=20)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_fits', to='teams.person')),
                ('person_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_fit_results', to='fit.bigfiveprofile')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_results', to='positions.position')),
            ],
            options={
                'verbose_name': 'résultat fit poste',
                'verbose_name_plural': 'résultats fit poste',
                'unique_together': {('person', 'position')},
            },
        ),
        migrations.CreateModel(
            name='TeamFitResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('openness_fit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fit ouverture')),
                ('conscientiousness_fit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fit conscienciosité')),
                ('extraversion_fit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fit extraversion')),
                ('agreeableness_fit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fit agréabilité')),
                ('neuroticism_fit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fit neuroticisme')),
                ('overall_fit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fit global')),
                ('complementarity', models.JSONField(default=dict, verbose_name='complémentarité')),
                ('team_size_at_computation', models.PositiveSmallIntegerField(default=0)),
                ('algorithm_version', models.CharField(default='v1.0', max_length=20)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_fits', to='teams.person')),
                ('person_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_fit_results', to='fit.bigfiveprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_results', to='teams.team')),
            ],
            options={
                'verbose_name': 'résultat fit équipe',
                'verbose_name_plural': 'résultats fit équipe',
                'unique_together': {('person', 'team')},
            },
        ),
    ]
