# Generated by Django 5.2.15 on 2026-07-03 16:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_positionfitresult_teamfitresult'),
        ('teams', '0002_team_department_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigFiveProfileHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('openness', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ouverture')),
                ('conscientiousness', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='conscienciosité')),
                ('extraversion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='extraversion')),
                ('agreeableness', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='agréabilité')),
                ('neuroticism', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='neuroticisme')),
                ('questionnaire_version', models.CharField(choices=[('50', '50 items'), ('100', '100 items')], max_length=3)),
                ('algorithm_version', models.CharField(default='v1.0', max_length=20)),
                ('computed_at', models.DateTimeField(verbose_name='calculé le')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_history', to='teams.person')),
            ],
            options={
                'verbose_name': 'historique profil Big Five',
                'verbose_name_plural': 'historique profils Big Five',
                'ordering': ['computed_at'],
            },
        ),
    ]
