# Generated by Django 5.2.15 on 2026-06-30 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fit', '0001_initial'),
        ('positions', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "journal d'audit",
                'verbose_name_plural': "journaux d'audit",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FitReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('JOB', 'Fit Poste'), ('TEAM', 'Fit Équipe')], max_length=4)),
                ('fit_openness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fit_conscientiousness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fit_extraversion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fit_agreeableness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fit_neuroticism', models.DecimalField(decimal_places=2, max_digits=5)),
                ('algorithm_version', models.CharField(default='v1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_reports', to='accounts.organization')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fit_reports', to='positions.position')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_reports', to='fit.bigfiveprofile')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fit_reports', to='teams.team')),
            ],
            options={
                'verbose_name': 'rapport de fit',
                'verbose_name_plural': 'rapports de fit',
                'ordering': ['-created_at'],
            },
        ),
    ]
