# Generated by Django 5.2.15 on 2026-07-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FitReport',
        ),
    ]
