# Generated by Django 5.2.15 on 2026-06-30 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('questionnaire_version', models.CharField(choices=[('50', '50 items'), ('100', '100 items')], default='50', max_length=3)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('expired', 'Expiré')], default='pending', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_links', to='accounts.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_links', to='teams.person')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lien questionnaire',
                'verbose_name_plural': 'liens questionnaire',
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('consent_version', models.CharField(default='v1.0', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('language', models.CharField(default='fr', max_length=2)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='survey.questionnairelink')),
            ],
            options={
                'verbose_name': 'consentement',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('current_item_index', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='survey.questionnairelink')),
            ],
            options={
                'verbose_name': 'session questionnaire',
            },
        ),
    ]
