# Generated by Django 5.2.15 on 2026-07-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_questionnairelink_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairelink',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
