# Generated by Django 5.2.15 on 2026-07-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_questionnairelink_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairelink',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('de', 'Deutsch')], default='fr', max_length=2),
        ),
    ]
